<?php

function getPubs() {

  $pubListSrc = "sites/all/modules/wri_external_pub_list/wriauthors.json";

  $pubList = file_get_contents($pubListSrc);

  $itemArray = json_decode($pubList, true);

  $extPub = $itemArray;

  $test = $extPub[0]['title'];

  return $test;

}


function searchForId($id, $array) {
   foreach ($array as $key => $val) {
       if ($val['type'] == $id) {
           //return $key;
           return $array[$key]['title'];
       }
   }
   return null;
}

$userdb = Array
(
    (0) => Array
        (
            ('uid') => '100',
            ('name') => 'Sandra Shush',
            ('url') => 'urlof100'
        ),

    (1) => Array
        (
            ('uid') => '5465',
            ('name') => 'Stefanie Mcmohn',
            ('pic_square') => 'urlof100'
        ),

    (2) => Array
        (
            ('uid') => '40489',
            ('name') => 'Michael',
            ('pic_square') => 'urlof40489'
        )
);

  $pubListSrc = "sites/all/modules/wri_external_pub_list/wriauthors.json";

  $pubList = file_get_contents($pubListSrc);

  $itemArray = json_decode($pubList, true);

  $extPub = $itemArray;


$id = searchForId('article-journal', $extPub);

$message = getPubs();

drupal_set_message(t($id), 'status');

