<?php

function getPubs() {

  $pubListSrc = "sites/all/modules/wri_external_pub_list/wriauthors.json";

  $pubList = file_get_contents($pubListSrc);

  $itemArray = json_decode($pubList, true);

  $extPub = $itemArray;

  $test = $extPub[0]['title'];

  return $test;

}

function searchForId($id, $array) {
   foreach ($array as $key => $val) {
       if ($val['volume'] == $id) {
           //return $key;
           return $array[$key]['title'];
       }
   }
   return null;
}

$userdb = Array
(
    (0) => Array
        (
            ('uid') => '100',
            ('name') => 'Sandra Shush',
            ('url') => 'urlof100'
        ),

    (1) => Array
        (
            ('uid') => '5465',
            ('name') => 'Stefanie Mcmohn',
            ('pic_square') => 'urlof100'
        ),

    (2) => Array
        (
            ('uid') => '40489',
            ('name') => 'Michael',
            ('pic_square') => 'urlof40489'
        )
);

  $pubListSrc = "sites/all/modules/wri_external_pub_list/wriauthors.json";

  $pubList = file_get_contents($pubListSrc);

  $itemArray = json_decode($pubList, true);

  $extPub = $itemArray;

  if (isset($_GET['foo'])){
    $testVar = $_GET['foo'];
  }
  else {
    $testVar = '11';
  }

$id = searchForId($testVar, $extPub);

$message = getPubs();

drupal_set_message(t($id), 'status');

/** 
* Create the Drupal blocks. 
*/

 /**
 * Implements hook_block_info().
 */

function wri_external_pub_list_block_info() {
  $blocks = array();
  $blocks['test'] = array(
    'info' => t('test info field'),
  );
  $blocks['external_publications'] = array(
    'info' => t('External Publications'),
    //'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */

function wri_external_pub_list_block_view($delta = '') {
  $block = array();
  switch ($delta) {
      case 'test';
      $block['subject'] = t('test subject');
      $block['title'] = t('test title');
      $block['content'] = t('test content');
      break;
    case 'external_publications':
      $the_block = 'hello pubs';
      $block['title'] = t('External Publications');
      $block['content'] = $the_block;
      break;
    }
  return $block;
}

